rapir/urls.py
from django.urls import path, include
from .views import *
from .feeds import LatestFeedRSS

urlpatterns = [
    path('news/', include([
        path('<slug:slug>', new, name='new'),
        path('', NewsList.as_view(), name='news'),
    ])),
    path('works/', include([
        path('<slug:slug>', work, name='work'),
        path('', WorksList.as_view(), name='works'),
    ])),
    path('explorations/', include([
        path('<slug:slug>', exploration, name='exploration'),
        path('', ExplorationsList.as_view(), name='explorations'),
    ])),
    path('about-us/', include([
        path('structure/people/people_<int:id>', person, name='expert'),
        path('structure/<str:position>/', workers, name='structure'),
        path('', about, name='about'),
    ])),
    path('galleries/', include([
        path('<slug:slug>', gallery, name='gallery'),
        path('', GalleriesList.as_view(), name='galleries'),
    ])),
    path('smi/', SmiList.as_view(), name='smi'),
    path('search/', SearchList.as_view(), name='search'),
    path('contact/', contact_view, name='contact'),
    path('lastnews/', LatestFeedRSS(), name='rss'),
    path('', main, name='main'),
]

rapir_site/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('rapir.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rapir/models.py
from django.db import models
from django.db.models import Q
from django.urls import reverse
from .forms import *


class SearchManager(models.Manager):
    use_for_related_fields = True

    def search(self, query=None):
        qs = self.get_queryset()
        if query:
            or_lookup = (Q(title__icontains=query) | Q(content__icontains=query))
            qs = qs.filter(or_lookup)

        return qs


class News(models.Model):
    title = models.CharField(max_length=75, verbose_name='Заголовок')
    slug = models.SlugField(max_length=90, unique=True)
    content = models.TextField(verbose_name='Текст')
    mini_content = models.TextField(max_length=90, verbose_name='Аннотация')
    published = models.DateField(db_index=True, verbose_name='Дата публикации')
    image = models.ImageField(verbose_name='Заставка новости', upload_to=f'news/%Y/%m/%d/', null=True, blank=True)
    file = models.FileField(verbose_name='Файл презентации в pdf', upload_to=f'news/%Y/%m/%d/', null=True, blank=True)
    objects = SearchManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('new', kwargs={'slug': self.slug})

    class Meta:
        verbose_name_plural = 'Новости'
        verbose_name = 'Новость'
        ordering = ['-published']


class People(models.Model):
    title = models.CharField(max_length=250, verbose_name='Имя')
    content = models.CharField(max_length=40, null=True, blank=True, verbose_name='Должность')
    avatar = models.ImageField(upload_to=f'person/%Y/%m/%d/', blank=True, null=True,
                               verbose_name='Фото человека')
    description = models.TextField(verbose_name='Описание')
    published = models.DateField(db_index=True, verbose_name='Дата публикации')
    objects = SearchManager()

    class Position(models.TextChoices):
        __empty__ = 'Выберете группу человека'
        expert = 'e', 'Экспертный совет'
        supervisor = 's', 'Наблюдательный совет'
        president = 'p', 'Президент фонда'
    position = models.CharField(max_length=1, choices=Position.choices, default=Position.__empty__,
                                verbose_name='Позиция')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('expert', kwargs={'id': self.id})

    class Meta:
        verbose_name_plural = 'Люди'
        verbose_name = 'Человек'


class Exploration(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.SlugField(max_length=120, unique=True)
    content = models.TextField(verbose_name='Текст')
    image = models.ImageField(verbose_name='Заставка новости', upload_to=f'works/%Y/%m/%d/', null=True, blank=True)
    file = models.FileField(verbose_name='Файл презентации в pdf', upload_to=f'works/%Y/%m/%d/', null=True, blank=True)
    published = models.DateField(db_index=True, verbose_name='Дата публикации')
    objects = SearchManager()

    def get_absolute_url(self):
        return reverse('exploration', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Исследования'
        verbose_name = 'Исследование'
        ordering = ['-published']


class Works(models.Model):
    title = models.CharField(max_length=30, verbose_name='Тип работы')
    subtitle = models.CharField(max_length=115, verbose_name='Заголовок')
    slug = models.SlugField(max_length=125, unique=True)
    content = models.TextField(verbose_name='Текст')
    file = models.FileField(verbose_name='Файл (pdf)', upload_to=f'works/%Y/%m/%d/', null=True, blank=True)
    counter = models.PositiveIntegerField(default=0, verbose_name='Кол-во загрузок')
    published = models.DateField(db_index=True, verbose_name='Дата публикации')
    objects = SearchManager()

    def get_absolute_url(self):
        return reverse('work', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Работы'
        verbose_name = 'Работа'
        ordering = ['-published']


class Smi(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    content = models.CharField(max_length=260, verbose_name='Текст')
    link = models.URLField(verbose_name='Ссылка на источник')
    slug = models.SlugField(max_length=160, unique=True)
    published = models.DateField(db_index=True, verbose_name='Дата публикации')
    objects = SearchManager()

    def get_absolute_url(self):
        return reverse('smi', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Мы в СМИ'
        verbose_name = 'Ссылка'
        ordering = ['-published']


class Album(models.Model):
    title = models.CharField(max_length=95, verbose_name='Заголовок')
    image = models.ImageField(verbose_name='Фото', upload_to='album/%Y/%m/%d/', null=False, blank=False)
    published = models.DateField(db_index=True, verbose_name='Дата публикации')
    slug = models.SlugField(max_length=95, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('gallery', kwargs={'slug': self.slug})

    class Meta:
        verbose_name_plural = 'Альбомы'
        verbose_name = 'Альбом'
        ordering = ['-published']


class Photo(models.Model):
    image = models.ImageField(verbose_name='Фото', upload_to='gallery/%Y/%m/%d/', null=False, blank=False)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Фото'
        verbose_name = 'Фото'
        ordering = ['-album']


class About(models.Model):
    history = models.TextField(verbose_name='История фонда')
    content1 = models.TextField(verbose_name='Текст 1 блока')
    image1 = models.ImageField(verbose_name='Картинка 1', upload_to='about/%Y/%m/%d/', null=False, blank=False)
    content2 = models.TextField(verbose_name='Текст 2 блока')
    image2_1 = models.ImageField(verbose_name='Картинка 2_1', upload_to='about/%Y/%m/%d/', null=False, blank=False)
    image2_2 = models.ImageField(verbose_name='Картинка 2_1', upload_to='about/%Y/%m/%d/', null=False, blank=False)
    content3 = models.TextField(verbose_name='Текст 3 блока')
    image3 = models.ImageField(verbose_name='Картинка 3', upload_to='about/%Y/%m/%d/', null=False, blank=False)

    class Meta:
        verbose_name_plural = 'Инфо без раздела'
        verbose_name = 'Текст'


class Slider(models.Model):
    title = models.CharField(max_length=120, verbose_name='Основной текст')
    content = models.TextField(verbose_name='Доп текст')
    image = models.ImageField(verbose_name='Картинка', upload_to='other/%Y/%m/%d/', null=False, blank=False)

    class Meta:
        verbose_name_plural = 'Фото на главной'
        verbose_name = 'фото'

rapir/forms.py
from django import forms


class ContactForm(forms.Form):
    email = forms.EmailField(label='Email', required=True)
    name = forms.CharField(label='Имя', required=True)
    mess = forms.CharField(label='Сообщение', widget=forms.Textarea, required=True)

rapir/views.py
from itertools import chain
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.mail import send_mail
from django.views.generic import ListView
from django.conf import settings

from .models import *
from .forms import ContactForm


class NewsList(ListView):
    model = News
    queryset = News.objects.all()
    template_name = 'rapir/news.html'
    paginate_by = 12


def new(request, slug):
    cur_new = News.objects.get(slug=slug)
    context = {'new': cur_new}
    return render(request, 'rapir/new.html', context)


class WorksList(ListView):
    model = Works
    queryset = Works.objects.all()
    template_name = 'rapir/projects.html'
    paginate_by = 12


def work(request, slug):
    cur_work = Works.objects.get(slug=slug)
    context = {'project': cur_work}
    return render(request, 'rapir/project.html', context)


class ExplorationsList(ListView):
    model = Exploration
    queryset = Exploration.objects.all()
    template_name = 'rapir/searches.html'
    paginate_by = 12


def exploration(request, slug):
    cur_exploration = Exploration.objects.get(slug=slug)
    context = {'search': cur_exploration}
    return render(request, 'rapir/search.html', context)


def main(request):
    last_news = News.objects.all()[:3]
    last_exploration = Exploration.objects.all()[:2]
    last_works = Works.objects.all()[:2]
    list_people = People.objects.all()
    slider = Slider.objects.all()

    context = {'last_news': last_news,
               'searches': last_exploration,
               'projects': last_works,
               'experts': list_people,
               'slider': slider}
    return render(request, 'rapir/index.html', context)


def workers(request, position):
    list_worker = People.objects.filter(position=position)
    context = {'experts': list_worker}
    if position == 'e':
        context['title'] = 'Экспертный совет'
    elif position == 's':
        context['title'] = 'Наблюдательный совет'
    return render(request, 'rapir/experts.html', context)


def person(request, id):
    worker = People.objects.get(id=id)
    context = {'expert': worker}
    return render(request, 'rapir/expert.html', context)


def about(request):
    list_worker = People.objects.all()
    other = About.objects.first()
    context = {'experts': list_worker,
               'about': other}
    return render(request, 'rapir/about.html', context)


class GalleriesList(ListView):
    model = Album
    queryset = Album.objects.all()
    template_name = 'rapir/galleries.html'
    paginate_by = 12

def gallery(request, slug):
    gal_lery = Photo.objects.filter(album__slug=slug)
    title = Album.objects.get(slug=slug)
    context = {'gallery': gal_lery,
               'album': title}
    return render(request, 'rapir/gallery.html', context)


class SmiList(ListView):
    model = Smi
    queryset = Smi.objects.all()
    template_name = 'rapir/mass_media.html'
    paginate_by = 12


class SearchList(ListView):
    template_name = 'rapir/search_result.html'
    paginate_by = 12

    def get_queryset(self):
        query_sets = []
        q = self.request.GET.get('q')
        query_sets.append(News.objects.search(query=q))
        query_sets.append(Works.objects.search(query=q))
        query_sets.append(Exploration.objects.search(query=q))
        query_sets.append(People.objects.search(query=q))

        # и объединяем выдачу
        final_set = list(chain(*query_sets))
        final_set.sort(key=lambda x: x.published, reverse=True)
        return final_set

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = f'q={self.request.GET.get("q")}&'
        return context


def contact_view(request):
    # если метод GET, вернем форму
    if request.method == 'GET':
        form = ContactForm()
    elif request.method == 'POST':
        # если метод POST, проверим форму и отправим письмо
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['mess']
            recepients = [settings.EMAIL_HOST_USER]
            send_mail(name + ' -- ' + email, message, settings.EMAIL_HOST_USER, recepients)
            return redirect('main')
    else:
        return HttpResponse('Неверный запрос.')
    return render(request, 'rapir/contact.html', {'form': form})

templates/rapir/contact.html
{% extends "rapir/layout/base.html" %}
{% load static %}
{% block title %}Ориентир | Контакты{% endblock %}
{% block content %}
<section class="experts-wrapper">
  <div class="push50"></div>
  <div class="container">
      <section class="contacts-section">
        <div class="contact-wrap">
			<!--Contacts item begin-->
			<div class="contacts-item contacts-item-first">
				<div class="contacts-inner-item">
					<h1>Контакты</h1>
					<div class="contacts-wrapper">
						<div class="adress"><i class="fa fa-map-marker" aria-hidden="true"></i> г. Ульяновск пр-т Ульяновский, д 13, 432072</div>
						<div class="push10"></div>
						<a href="tel:+79372711122" class="phone"> <i class="fa fa-phone" aria-hidden="true"></i>+7 (937) 271-11-22</a>
						<div class="push10"></div>
						<a href="mailto:is_orientir@mail.ru" class="email"><i class="fa fa-envelope" aria-hidden="true"></i>is_orientir@mail.ru</a>
						<div class="push15"></div>
						<div class="social">
							<!--a href="#" class="fcb"><i class="fa fa-facebook"></i></a>
							<a href="#" class="vk"><i class="fa fa-vk"></i></a-->
							<a href="#" class="rss"><i class="fa fa-rss"></i></a>
						</div>
						<div class="push30"></div>
            <div class="map-contact contacts-inner-item">
              <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A4e1466e62f87da2ca1a5e9ec67d67bcd90d849d3ef6412a07f8b501c1fdefaeb&amp;width=100%25&amp;height=250&amp;lang=ru_RU&amp;scroll=true"></script>
            </div>
					</div>
				</div>
				
          </div>
          <!--Contacts item end-->
          <!--Contacts item begin-->
          <div class="contacts-item contacts-item-form">
            <div class="form-header">Для вопросов и предложений</div>
            <form method="post" class="form-contact form">
              {% csrf_token %}
                  <div class="form-body">
                      <div class="form-group">
                          <input name="name" placeholder="Ваше имя*" type="text" class="text" required />
                      </div>
                      <div class="form-group">
                          <input name="email" placeholder="Ваш Email*" type="email" class="text" required/>
                      </div>
                      <div class="form-group">
                        <textarea name="mess" placeholder="Введите сообщение..."></textarea>
                      </div>
                  </div>
                  <div class="form-actions form-group ">
                      <button type="submit" class="form-control btn btn-success button button-form" name="sendform">Отправить</button>
                  </div>
            </form>
          </div>
          <!--Contacts item end-->
          
        </div>
      </section>
      <div class="push100"></div>
  </div>
</section>
{% endblock %}

templates/rapir/expert.html
{% extends "rapir/layout/base.html" %}
{% load static %}
{% block title %}РАПИР | {{ expert.title }}{% endblock %}
{% block content %}
        <div class="about-exp-wrapper">
            <div class="container">
                <div class="push50"></div>

                <div class="about-exp-inner">
                    <div class="about-exp-image visible-xs">
                        {% if expert.image %}
                            <img src="{{ expert.avatar.url }}" alt="Эксперт"/>
                        {% endif %}
                    </div>
                    <div class="about-exp-text ">
                        <div class="about-exp-image hidden-xs">
                            {% if expert.image %}
                                <img src="{{ expert.avatar.url }}" alt="Эксперт"/>
                            {% endif %}
                        </div>
                        <h1>{{ expert.title }}</h1>
                        <h2>{{ expert.content }}</h2>
                        <p>{{ expert.description | safe }}</p>
                    </div>
                </div>
                <div class="push50"></div>
            </div>
        </div>
{% endblock %}

templates/rapir/experts.html
{% extends "rapir/layout/base.html" %}
{% load static %}
{% block title %}Ориентир | Эксперты{% endblock %}
{% block content %}
<div class="participant-page">
    <section class="participant-section">
        <hr>
        <div class="push50"></div>
        <div class="container">
            <div class="participant-wrapper">
                <div class="participant-header">
                    <div class="text-header">
                        <h2>Специалисты и эксперты центра</h2>
                        <div class="push20"></div>
                    </div>
                    <hr>
                    <div class="push30"></div>
                    <div class="subtitle">
                        <p>
                            Amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.
                        </p>
                    </div>
                    <div class="push50"></div>
                </div>
                <div class="participants-wrap">
                    <!--=======================Participants item begin=======================-->
                    {% for expert in experts %}
                       <!--div class="experts-item">
						<div class="expert-inner">
							<div class="image-wrapper">
								{% if expert.avatar %}
								<img src="{{ expert.avatar.url }}" alt="expert"/>
							{% else %}
								<img src="{% static 'rapir/images/empty.png' %}" alt="expert">
							{% endif %}
							</div>
							<div class="experts-text">
								<div class="title-wrapper">
									{{ expert.name }}
								</div>
								<div class="push10"></div>
								<div class="description-wrapper">
									{{ expert.description }}
								</div>
							</div>
						</div>
					</div-->
                    {% endfor %}
                    <div class="experts-item">
                        <div class="expert-inner">
                            <div class="image-wrapper">
                                <img src="{% static 'rapir/images/ph1.jpg' %}" alt="expert"/>
                            </div>
                            <div class="experts-text">
                                <div class="title-wrapper">
                                    Баханова Елена Викторовна
                                </div>
                                <div class="push10"></div>
                                <div class="description-wrapper">
                                    психолог, кандидат социологических наук, докторант, имеет более 60 публикаций и учебных пособий, в том числе 3 монографии
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="experts-item">
                        <div class="expert-inner">
                            <div class="image-wrapper">
                                <img src="{% static 'rapir/images/ph1.jpg' %}" alt="expert"/>
                            </div>
                            <div class="experts-text">
                                <div class="title-wrapper">
                                    Башарина Алла Викторовна
                                </div>
                                <div class="push10"></div>
                                <div class="description-wrapper">
                                    Кандидат социологических наук, магистр юриспруденции
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="experts-item">
                        <div class="expert-inner">
                            <div class="image-wrapper">
                                <img src="{% static 'rapir/images/ph1.jpg' %}" alt="expert"/>
                            </div>
                            <div class="experts-text">
                                <div class="title-wrapper">
                                    Игонина Наталья Валентиновна
                                </div>
                                <div class="push10"></div>
                                <div class="description-wrapper">
                                    Директор Медицинского центра "Медсовет", диетолог, специалист по ведению здорового образа жизни
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="experts-item">
                        <div class="expert-inner">
                            <div class="image-wrapper">
                                <img src="{% static 'rapir/images/ph9.jpg' %}" alt="expert"/>
                            </div>
                            <div class="experts-text">
                                <div class="title-wrapper">
                                    Сибагатулина Елена Ивановна
                                </div>
                                <div class="push10"></div>
                                <div class="description-wrapper">
                                    председатель Ульяновское региональное отделение общероссийской общественной организации «Российский Красный Крест»
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="experts-item">
                        <div class="expert-inner">
                            <div class="image-wrapper">
                                <img src="{% static 'rapir/images/ph1.jpg' %}" alt="expert"/>
                            </div>
                            <div class="experts-text">
                                <div class="title-wrapper">
                                    Баханова Елена Викторовна
                                </div>
                                <div class="push10"></div>
                                <div class="description-wrapper">
                                    психолог, кандидат социологических наук, докторант, имеет более 60 публикаций и учебных пособий, в том числе 3 монографии
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="experts-item">
                        <div class="expert-inner">
                            <div class="image-wrapper">
                                <img src="{% static 'rapir/images/ph9.jpg' %}" alt="expert"/>
                            </div>
                            <div class="experts-text">
                                <div class="title-wrapper">
                                    Башарина Алла Викторовна
                                </div>
                                <div class="push10"></div>
                                <div class="description-wrapper">
                                    Кандидат социологических наук, магистр юриспруденции
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="experts-item">
                        <div class="expert-inner">
                            <div class="image-wrapper">
                                <img src="{% static 'rapir/images/ph1.jpg' %}" alt="expert"/>
                            </div>
                            <div class="experts-text">
                                <div class="title-wrapper">
                                    Игонина Наталья Валентиновна
                                </div>
                                <div class="push10"></div>
                                <div class="description-wrapper">
                                    Директор Медицинского центра "Медсовет", диетолог, специалист по ведению здорового образа жизни
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="experts-item">
                        <div class="expert-inner">
                            <div class="image-wrapper">
                                <img src="{% static 'rapir/images/ph9.jpg' %}" alt="expert"/>
                            </div>
                            <div class="experts-text">
                                <div class="title-wrapper">
                                    Сибагатулина Елена Ивановна
                                </div>
                                <div class="push10"></div>
                                <div class="description-wrapper">
                                    председатель Ульяновское региональное отделение общероссийской общественной организации «Российский Красный Крест»
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <!--=======================Participants item end=======================-->
                </div>
                <div class="button-wrap hidden-lg hidden-md">
                    <a class="button" href="{% url 'structure' 'e' %}">Смотреть все</a>
                </div>
            </div>
        </div>
        <div class="push70"></div>
    </section>
    <div class="push50"></div>
    {% endblock %}
</div>

templates/rapir/mass_media.html
{% extends "rapir/layout/base.html" %}
{% load static %}
{% block title %}РАПИР | Мы в СМИ{% endblock %}
{% block content %}

<section class="mass-media-section">
	<div class="container">
		<div class="push50"></div>
		<h2>Мы в СМИ</h2>
		<div class="push20"></div>
		<div class="mass-media-wrapper">
			{% for mm in smi_list %}
			<div class="mass-media-item">
				<a class="link-block" href="{{ mm.link }}" target="_blank"></a>
				<div class="mass-media-text">
					<div class="mass-media-title">
						{{ mm.title }}
					</div>
					<div class="mass-media-annotation">
						{{ mm.content }}
					</div>
				</div>
				<a class="readmore" href="{{ mm.link }}">Подробнее <span>>></span></a>
			</div>
			{% endfor %}
		</div>
        {% include 'rapir/pagination.html' %}
		<div class="push50"></div>
	</div>
</section>

{% endblock %}

templates/rapir/new.html
{% extends "rapir/layout/base.html" %}
{% load static %}
{% block title %}Ориентир | {{ new.title }}{% endblock %}
{% block content %}
<hr>
<section class="news-page-section">
	<div class="container">
		<div class="news-page-wrapper">
			<div class="push50"></div>
			<div class="news-img visible-lg visible-md">
                {% if new.image %}
				    <img src="{{ new.image.url }}" alt="new">
                {% endif %}
			</div>
			<h1>{{ new.title }}</h1>
			<div class="push20"></div>
			<h4>{{ new.published|date:"d.m.Y" }}</h4>
			<div class="push20"></div>
			<h3>{{ new.mini_content }}</h3>
			<div class="push20"></div>
			<div class="news-img hidden-lg hidden-md">
				{% if new.image %}
				    <img src="{{ new.image.url }}" alt="new">
                {% endif %}
			</div>
			<div class="content">
				<p>{{ new.content | safe }}</p>
            </div>
			<div class="push20"></div>
            {% if new.file %}
                <iframe id="pres" src="{{ new.file.url }}"></iframe>
            {% endif %}
			<div class="push50"></div>
		</div>
	</div>
</section>

{% endblock %}

templates/rapir/project.html
{% extends "rapir/layout/base.html" %}
{% load static %}
{% block title %}Ориентир | {{ project.subtitle }}{% endblock %}
{% block content %}
<hr>
<section class="event-page-section">
	<div class="container">
		<div class="event-page-wrapper">
			<div class="push20"></div>
			<h1>{{ project.subtitle }}</h1>
			<div class="push20"></div>
			<div class="content">
				<p>{{ project.content | safe }}</p>
			</div>
			<div class="push20"></div>

            {% if project.file %}
                <!--Презентация-->
                <iframe src="{{ project.file.url }}"></iframe>
                <div class="push20"></div>
                <!--Ссылка на скачивание презентации-->
                <a href="{{ project.file.url }}" download class="button">Скачать файл</a>
            {% endif %}
			<div class="push50"></div>
		</div>
	</div>
</section>

{% endblock %}

templates/rapir/search.html
{% extends "rapir/layout/base.html" %}
{% load static %}
{% block title %}РАПИР | {{ search.title }}{% endblock %}
{% block content %}

<section class="event-page-section">
	<div class="container">
		<div class="event-page-wrapper">
			<div class="push50"></div>
			<h1>{{ search.title }}</h1>
			<div class="push10"></div>
			<div class="content">
				<p>{{ search.content | safe }}</p>
			</div>
			 {% if search.file %}
                <div class="push20"></div>
                <!--Презентация-->
                <iframe id="pres" src="{{ search.file.url }}"></iframe>
                <div class="push20"></div>
                <!--Ссылка на скачивание презентации-->
                <a href="{{ search.file.url }}" download class="button">Скачать презентацию</a>
            {% endif %}
			<div class="push50"></div>
		</div>
	</div>
</section>

{% endblock %}

templates/rapir/searches.html
{% extends "rapir/layout/base.html" %}
{% load static %}
{% block title %}РАПИР | Исследования{% endblock %}
{% block content %}

<section class="searches-section">
	<div class="container">
		<div class="push50"></div>
		<h1>Исследования</h1>
		<div class="push50"></div>
		<div class="searches-wrapper section-item-wrapper">
			{% for search in exploration_list %}
			<a href="{{ search.get_absolute_url }}" class="section-item">
                <div class="image-wrap">
                    {% if search.image %}
					    <img src="{{ search.image.url }}" alt="">
                    {% else %}
                        <img src="{% static 'rapir/images/empty.png' %}" alt="new">
                    {% endif %}
                </div>
                <div class="title-wrap">
                    {{ search.title }}
                </div>
            </a>
            {% endfor %}
		</div>
        {% include 'rapir/pagination.html' %}
		<div class="push100"></div>
	</div>
</section>

{% endblock %}